# Site Settings
title: Jenkov | A Blog for Jenkov Deng
email: youremail@xyz.com
description: Some text about your blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://smilegithub01.github.io" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Jenkov
user_description: Some text about you.
disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: smilegithub01
facebook_username: 邓阿康
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: 邓阿康
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 12
paginate_path: "/page/:num/"
svg_color: "#ff0a16"

# Plugins
plugins:
  - jemoji
  - jekyll-paginate

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
